---
title: "Psych 254 Replication Project Analysis"
author: "Eric Smith, Robert Hawkins, Michael C. Frank"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(dplyr)
library(ggplot2)
library(googlesheets)
library(readr)
library(tidyr)
```

Get project planning sheet straight from google docs. 

```{r}
project_plan_sheet <- gs_url("https://docs.google.com/spreadsheets/d/1KZw75xlypvtK0cDoOHqXfFd3HsrfJ4gbq8iEJ6LOa0Y", lookup = TRUE) # Need lookup=T to initialize
project_plan_raw <- gs_read_csv(project_plan_sheet)
```

Exclude those to be excluded. 

```{r}
project_plan <- project_plan_raw %>%
  filter(`include_in_final_writeup`==1) 
```

Read in project_info data from each project

```{r}
errors <- list()# Initialize an error var

all_project_info <- data.frame( # initialize an empty dataframe
  project_key = character()
)

project_keys <- project_plan$project_key # Find user names that are included in 

passing <- c("mkeil","jreynolds","jmarias","jsalloum","ehermann",
             "jedtan", "lampinen", "salehi")
failing <- c("auc", "rhiac", "sraposo")

# Run all respective R code - need loop because project_keys same variable name
for(project_key in passing) { # project_keys
  fp <- paste0("project_analyses/",project_key,".R")
  
  print(fp)
  
  tryCatch(source(fp), 
           error = function(e) {
             errors <- c(errors, paste0(project_key," has an error in .R file"))
             }
           ) 
  
  # If has project_info dataframe, add to all data
  if(exists("project_info")) { 
    all_project_info <- bind_rows(all_project_info,project_info) 
    # rm("project_info") # In case other file does not same
  } else {
    errors <- c(errors,paste0(project_key," is missing project_info"))
  }
}
```
