---
  title: "Psych 254 Replication Project Analysis"
author: "Eric Smith, Robert Hawkins, Michael C. Frank"
date: '`r Sys.Date()`'
output:
  html_document:
  number_sections: yes
toc: yes
---
  
Assessing the Replicability of Psychological Science Through Pedagogy




Contributions
Pedagogical recipe
Toolset (dplyr, ggplot, mturk, etc)
Author contact template
Course experiment templates
Extraction of key statistic, power analysis
Multiple reviews by team
Pre-registration
Proof of concept
Table w/ all included replications
Scatter plot of effect sizes?
Actual findings


Methods

Class Methods

Participants

IRB

Individual Replications

Preregistration

Project preregistration: https://osf.io/rxz8m/
  
  Results

Pedagogical assessment 

how many replications were conducted to the intended standard, how many opted out etc. 

Assessing the fidelity of replications to the original (in terms of same sample, same materials, same task parameters) 

Scientific Assessment

Indices of replicability 


Coding of previous years’ findings

Discussion

Importance of self-selected papers - these are the papers that interesting to next generation of researchers

How to archive and make searchable the results of this sort of class?
OSF - but need search tools
PsychFileDrawer
CurateScience

Supplemental

All materials that are needed for class to implement
Email templates
Spreadsheets
TA/prof auditing processes
